import SwiftUI
import WebKit
import UIKit

/// One runnable artifact extracted from a message. Mirrors the web side panel's
/// model: html/svg are "runnable" (rendered live), everything else shows as code.
struct Artifact: Identifiable {
    let id = UUID()
    let lang: String        // "html" | "svg"
    let code: String
    var runnable: Bool { lang == "html" || lang == "svg" }
}

/// Renders trusted artifact HTML/SVG locally in a WKWebView. This is the native
/// equivalent of the web app's <iframe srcDoc>. JS is allowed (games/websites
/// need it); content is generated by the user's own model, loaded with no base
/// URL so it can't reach app-local resources.
struct ArtifactWebView: UIViewRepresentable {
    let html: String

    func makeUIView(context: Context) -> WKWebView {
        let cfg = WKWebViewConfiguration()
        cfg.defaultWebpagePreferences.allowsContentJavaScript = true
        let wv = WKWebView(frame: .zero, configuration: cfg)
        wv.isOpaque = false
        wv.backgroundColor = .clear
        wv.scrollView.backgroundColor = .clear
        return wv
    }

    func updateUIView(_ wv: WKWebView, context: Context) {
        wv.loadHTMLString(html, baseURL: nil)
    }
}

/// Full-screen artifact sheet: Preview / Code toggle, Copy, and (box mode only)
/// Publish — POSTing to the box's /publish-artifact and handing back a share URL.
struct ArtifactView: View {
    let artifact: Artifact
    let boxConfig: BoxClient.Config?

    @Environment(\.dismiss) private var dismiss
    @State private var tab: Tab = .preview
    @State private var publish: PublishState = .idle

    enum Tab: Hashable { case preview, code }
    enum PublishState: Equatable { case idle, working, done(String), failed }

    /// SVG gets wrapped/centred exactly like the web side panel; HTML loads raw.
    private var srcDoc: String {
        artifact.lang == "svg"
            ? "<!doctype html><meta charset=\"utf-8\"><body style=\"margin:0;display:grid;place-items:center;min-height:100vh\">\(artifact.code)</body>"
            : artifact.code
    }

    var body: some View {
        NavigationStack {
            content
                .navigationTitle("\(artifact.lang.uppercased()) artifact")
                .navigationBarTitleDisplayMode(.inline)
                .toolbar {
                    ToolbarItem(placement: .topBarLeading) {
                        Button("Done") { dismiss() }
                    }
                    if artifact.runnable {
                        ToolbarItem(placement: .principal) {
                            Picker("", selection: $tab) {
                                Text("Preview").tag(Tab.preview)
                                Text("Code").tag(Tab.code)
                            }
                            .pickerStyle(.segmented)
                            .frame(width: 170)
                        }
                    }
                    ToolbarItemGroup(placement: .topBarTrailing) {
                        Button {
                            UIPasteboard.general.string = artifact.code
                            UIImpactFeedbackGenerator(style: .light).impactOccurred()
                        } label: { Image(systemName: "doc.on.doc") }

                        if boxConfig != nil && artifact.runnable {
                            publishButton
                        }
                    }
                }
        }
    }

    @ViewBuilder private var content: some View {
        if tab == .preview && artifact.runnable {
            ArtifactWebView(html: srcDoc).ignoresSafeArea(edges: .bottom)
        } else {
            ScrollView([.horizontal, .vertical]) {
                Text(artifact.code)
                    .font(.system(.footnote, design: .monospaced))
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding()
            }
        }
    }

    @ViewBuilder private var publishButton: some View {
        switch publish {
        case .idle:
            Button { runPublish() } label: { Image(systemName: "square.and.arrow.up") }
        case .working:
            ProgressView()
        case .done(let url):
            Button {
                UIPasteboard.general.string = url
                UINotificationFeedbackGenerator().notificationOccurred(.success)
            } label: { Image(systemName: "checkmark.circle.fill").foregroundStyle(.green) }
        case .failed:
            Button { runPublish() } label: {
                Image(systemName: "exclamationmark.triangle").foregroundStyle(.orange)
            }
        }
    }

    private func runPublish() {
        guard let cfg = boxConfig else { return }
        publish = .working
        Task {
            do {
                let url = try await ArtifactPublisher.publish(html: srcDoc, config: cfg)
                await MainActor.run { publish = .done(url) }
            } catch {
                await MainActor.run { publish = .failed }
            }
        }
    }
}

/// POSTs an artifact to the box gateway's /publish-artifact and returns the
/// public share URL. Matches the web app's publish flow (Bearer key + {html},
/// response { id, path }).
enum ArtifactPublisher {
    static func publish(html: String, config: BoxClient.Config) async throws -> String {
        var base = config.tunnelUrl
        while base.hasSuffix("/") { base.removeLast() }

        guard let url = URL(string: "\(base)/publish-artifact") else {
            throw URLError(.badURL)
        }
        var req = URLRequest(url: url)
        req.httpMethod = "POST"
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.setValue("Bearer \(config.apiKey)", forHTTPHeaderField: "Authorization")
        req.httpBody = try JSONSerialization.data(withJSONObject: ["html": html])

        let (data, resp) = try await URLSession.shared.data(for: req)
        guard let http = resp as? HTTPURLResponse, http.statusCode == 200 else {
            throw URLError(.badServerResponse)
        }
        guard
            let obj = try JSONSerialization.jsonObject(with: data) as? [String: Any],
            let path = obj["path"] as? String
        else { throw URLError(.cannotParseResponse) }
        return "\(base)\(path)"
    }
}
